version: '3.8'

services:
  backend:
    image: test-ai-project-rg/backend:latest 
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5433/${POSTGRES_DB}
      - HOST=0.0.0.0
      - PORT=8000
      - ALLOW_ORIGINS=http://localhost,http://localhost:3000,http://frontend:5173
    depends_on:
      - db
      - elasticsearch

  frontend:
    image: test-ai-project-rg/frontend:latest  
    ports:
      - "5173:5173"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend

  db:
    image: postgres:14
    ports:
      - "5434:5433"
    command: -p 5433
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
