"""add user use_cases relationship

Revision ID: 14279c96f79e
Revises: ca84e52c5d1d
Create Date: 2025-03-12 14:12:12.322425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14279c96f79e'
down_revision: Union[str, None] = 'ca84e52c5d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('use_cases', 'date_created',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_constraint('use_cases_submitted_by_fkey', 'use_cases', type_='foreignkey')
    op.create_foreign_key(None, 'use_cases', 'users', ['submitted_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'use_cases', type_='foreignkey')
    op.create_foreign_key('use_cases_submitted_by_fkey', 'use_cases', 'users', ['submitted_by'], ['id'])
    op.alter_column('use_cases', 'date_created',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    # ### end Alembic commands ###
