"""date_created changes

Revision ID: 195330acb11b
Revises: a820128ac10e
Create Date: 2025-03-13 12:36:47.577867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195330acb11b'
down_revision: Union[str, None] = 'a820128ac10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('institution_name_idx', table_name='institutions')
    op.alter_column('use_cases', 'date_created',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('use_cases', 'date_created',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.create_index('institution_name_idx', 'institutions', ['name'], unique=False)
    # ### end Alembic commands ###
