"""add latitud and longitud columns to institutions table

Revision ID: 1d88edab9c4c
Revises: 8dcaf367ad0a
Create Date: 2025-03-17 17:06:40.452340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d88edab9c4c'
down_revision: Union[str, None] = '8dcaf367ad0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('latitude', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('institutions', sa.Column('longitude', sa.Float(), nullable=False, server_default='0.0'))
    op.drop_column('institutions', 'coordinates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('coordinates', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('institutions', 'longitude')
    op.drop_column('institutions', 'latitude')
    # ### end Alembic commands ###
