"""add state column to institutions table

Revision ID: 8dcaf367ad0a
Revises: 195330acb11b
Create Date: 2025-03-17 16:33:35.838192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dcaf367ad0a'
down_revision: Union[str, None] = '195330acb11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('state', sa.String(), nullable=False, server_default='Unknown'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'state')
    # ### end Alembic commands ###
