"""update institution structure

Revision ID: a820128ac10e
Revises: 14279c96f79e
Create Date: 2025-03-12 18:34:43.788913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a820128ac10e'
down_revision: Union[str, None] = '14279c96f79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with temporary default values
    op.add_column('institutions', sa.Column('country', sa.String(), nullable=False, server_default='Unknown'))
    op.add_column('institutions', sa.Column('city', sa.String(), nullable=False, server_default='Unknown'))
    op.add_column('institutions', sa.Column('coordinates', sa.Float(), nullable=False, server_default='0.0'))
    
    # Then create the index
    op.create_index('institution_name_idx', 'institutions', ['name'])
    op.drop_column('institutions', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('institution_name_idx', 'institutions')
    op.drop_column('institutions', 'coordinates')
    op.drop_column('institutions', 'city')
    op.drop_column('institutions', 'country')
    # ### end Alembic commands ###
